rule all:
    input: "data/SOM/clusters_7_7_coverage_matrix"

rule coverage_matrix:
    input: "data/SOM/clusters_{dim1,\d+}_{dim2,\d+}"
    output: directory("data/SOM/clusters_{dim1,\d+}_{dim2,\d+}_coverage_matrix")
    shell: "mkdir {output}"

rule codebook_clustering:
    input: "data/SOM/codes_{dim1,\d+}_{dim2,\d+}.txt"
    output: directory("data/SOM/clusters_{dim1,\d+}_{dim2,\d+}")
    shell: "python clustering_som.py --input {input} --output_dir {output}"

rule SOM:
    input: "data/Features/all_data_ts_clean_v2.txt"
    output: "data/SOM/codes_{dim1,\d+}_{dim2,\d+}.txt"
    conda: "envs/SOM_clustering.yaml"
    shell: "Rscript SOM_grid_search.R {input} {output} {wildcards.dim1} {wildcards.dim2} 1"
