rule all:
    input: "data/clusters"

rule codebook_clustering:
    input: "data/SOM/codes_48_48.txt"
    output: directory("data/clusters")
    shell: "python clustering_som.py --input {input} --output_dir {output}"

rule coverage_matrix:
    input: "TODO"
    output: directory("TODO")
    shell: "Rscript TODO"

rule SOM:
    input: "data/Features/all_data_ts_clean_v2.txt"
    output: "data/SOM/codes_48_48.txt"
    conda: "envs/SOM_clustering.yaml"
    shell: "Rscript SOM_grid_search.R 48 {input} {output}"
